### ISSUE TITLE
Call to undefined method ReflectionUnionType::getName()

### ISSUE THREAD

**Issue by arnoudhgz** [EmicoEcommerce/Magento2TweakwiseExport#16]
Issue Brief
--
What is the purpose of this issue? Explain the background context.

Environment
--
- [x] PHP Version: 8.1.4
- [x] Magento Version: 2.4.4-p3
- [x] Magento Enterprise: yes
- [x] Tweakwise Export Version: 5.3.1
- [x] Magento Deploy Mode: both
- [x] Third party modules: no

Steps to reproduce
--
1. Install Magento from `master` branch.
2. Install Export module with version 5.3.1
4. Enable the module
5. Run bin/magento setup:di:compile / bin/magento tweakwise:export

Actual result
--
1. Compilation / Runtime error
```
Call to undefined method ReflectionUnionType::getName()#0 ~/projects/acme/vendor/magento/framework/Code/Generator/EntityAbstract.php(393): Magento\Framework\Code\Generator\EntityAbstract->extractParameterType()
#1 ~/projects/acme/vendor/magento/framework/ObjectManager/Code/Generator/Proxy.php(176): Magento\Framework\Code\Generator\EntityAbstract->_getMethodParameterInfo()
#2 ~/projects/acme/vendor/magento/framework/ObjectManager/Code/Generator/Proxy.php(136): Magento\Framework\ObjectManager\Code\Generator\Proxy->_getMethodInfo()
#3 ~/projects/acme/vendor/magento/framework/Code/Generator/EntityAbstract.php(226): Magento\Framework\ObjectManager\Code\Generator\Proxy->_getClassMethods()
#4 ~/projects/acme/vendor/magento/framework/ObjectManager/Code/Generator/Proxy.php(160): Magento\Framework\Code\Generator\EntityAbstract->_generateCode()
#5 ~/projects/acme/vendor/magento/framework/Code/Generator/EntityAbstract.php(106): Magento\Framework\ObjectManager\Code\Generator\Proxy->_generateCode()
#6 ~/projects/acme/vendor/magento/framework/Code/Generator.php(130): Magento\Framework\Code\Generator\EntityAbstract->generate()
#7 ~/projects/acme/vendor/magento/framework/Code/Generator/Autoloader.php(53): Magento\Framework\Code\Generator->generateClass()
#8 [internal function]: Magento\Framework\Code\Generator\Autoloader->load()
#9 ~/projects/acme/vendor/magento/framework/ObjectManager/Relations/Runtime.php(38): class_exists()
#10 ~/projects/acme/vendor/magento/framework/Interception/Config/Config.php(157): Magento\Framework\ObjectManager\Relations\Runtime->has()
#11 ~/projects/acme/vendor/magento/framework/Interception/Config/Config.php(180): Magento\Framework\Interception\Config\Config->_inheritInterception()
#12 ~/projects/acme/vendor/magento/framework/Interception/ObjectManager/Config/Developer.php(61): Magento\Framework\Interception\Config\Config->hasPlugins()
#13 ~/projects/acme/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(47): Magento\Framework\Interception\ObjectManager\Config\Developer->getInstanceType()
#14 ~/projects/acme/vendor/magento/framework/ObjectManager/ObjectManager.php(70): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create()
#15 ~/projects/acme/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(206): Magento\Framework\ObjectManager\ObjectManager->get()
#16 ~/projects/acme/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(182): Magento\Framework\ObjectManager\Factory\AbstractFactory->parseArray()
#17 ~/projects/acme/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(276): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument()
#18 ~/projects/acme/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(239): Magento\Framework\ObjectManager\Factory\AbstractFactory->getResolvedArgument()
#19 ~/projects/acme/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(34): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgumentsInRuntime()
#20 ~/projects/acme/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(59): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments()
#21 ~/projects/acme/vendor/magento/framework/ObjectManager/ObjectManager.php(70): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create()
#22 ~/projects/acme/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(206): Magento\Framework\ObjectManager\ObjectManager->get()
#23 ~/projects/acme/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(182): Magento\Framework\ObjectManager\Factory\AbstractFactory->parseArray()
#24 ~/projects/acme/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(276): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument()
#25 ~/projects/acme/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(239): Magento\Framework\ObjectManager\Factory\AbstractFactory->getResolvedArgument()
#26 ~/projects/acme/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(34): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgumentsInRuntime()
#27 ~/projects/acme/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(59): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments()
#28 ~/projects/acme/vendor/magento/framework/ObjectManager/ObjectManager.php(70): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create()
#29 ~/projects/acme/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(170): Magento\Framework\ObjectManager\ObjectManager->get()
#30 ~/projects/acme/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(276): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument()
#31 ~/projects/acme/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(239): Magento\Framework\ObjectManager\Factory\AbstractFactory->getResolvedArgument()
#32 ~/projects/acme/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(34): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgumentsInRuntime()
#33 ~/projects/acme/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(59): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments()
#34 ~/projects/acme/vendor/magento/framework/ObjectManager/ObjectManager.php(70): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create()
#35 ~/projects/acme/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(206): Magento\Framework\ObjectManager\ObjectManager->get()
#36 ~/projects/acme/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(182): Magento\Framework\ObjectManager\Factory\AbstractFactory->parseArray()
#37 ~/projects/acme/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(276): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument()
#38 ~/projects/acme/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(239): Magento\Framework\ObjectManager\Factory\AbstractFactory->getResolvedArgument()
#39 ~/projects/acme/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(34): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgumentsInRuntime()
#40 ~/projects/acme/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(59): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments()
#41 ~/projects/acme/vendor/magento/framework/ObjectManager/ObjectManager.php(70): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create()
#42 ~/projects/acme/generated/code/Tweakwise/Magento2TweakwiseExport/Model/Write/Writer/Proxy.php(84): Magento\Framework\ObjectManager\ObjectManager->get()
#43 ~/projects/acme/generated/code/Tweakwise/Magento2TweakwiseExport/Model/Write/Writer/Proxy.php(127): Tweakwise\Magento2TweakwiseExport\Model\Write\Writer\Proxy->_getSubject()
#44 ~/projects/acme/vendor/tweakwise/magento2-tweakwise-export/Model/Export.php(182): Tweakwise\Magento2TweakwiseExport\Model\Write\Writer\Proxy->write()
#45 ~/projects/acme/vendor/tweakwise/magento2-tweakwise-export/Model/Export.php(96): Tweakwise\Magento2TweakwiseExport\Model\Export->Tweakwise\Magento2TweakwiseExport\Model\{closure}()
#46 ~/projects/acme/vendor/tweakwise/magento2-tweakwise-export/Model/Export.php(171): Tweakwise\Magento2TweakwiseExport\Model\Export->executeLocked()
#47 ~/projects/acme/generated/code/Tweakwise/Magento2TweakwiseExport/Model/Export/Proxy.php(111): Tweakwise\Magento2TweakwiseExport\Model\Export->generateToFile()
#48 ~/projects/acme/vendor/tweakwise/magento2-tweakwise-export/Console/Command/ExportCommand.php(157): Tweakwise\Magento2TweakwiseExport\Model\Export\Proxy->generateToFile()
#49 [internal function]: Tweakwise\Magento2TweakwiseExport\Console\Command\ExportCommand->Tweakwise\Magento2TweakwiseExport\Console\Command\{closure}()
#50 ~/projects/acme/vendor/magento/framework/App/State.php(187): call_user_func_array()
#51 ~/projects/acme/generated/code/Magento/Framework/App/State/Interceptor.php(68): Magento\Framework\App\State->emulateAreaCode()
#52 ~/projects/acme/vendor/tweakwise/magento2-tweakwise-export/Console/Command/ExportCommand.php(168): Magento\Framework\App\State\Interceptor->emulateAreaCode()
#53 ~/projects/acme/vendor/symfony/console/Command/Command.php(255): Tweakwise\Magento2TweakwiseExport\Console\Command\ExportCommand->execute()
#54 ~/projects/acme/vendor/magento/framework/Interception/Interceptor.php(58): Symfony\Component\Console\Command\Command->run()
#55 ~/projects/acme/vendor/magento/framework/Interception/Interceptor.php(138): Tweakwise\Magento2TweakwiseExport\Console\Command\ExportCommand\Interceptor->___callParent()
#56 ~/projects/acme/vendor/magento/framework/Interception/Interceptor.php(153): Tweakwise\Magento2TweakwiseExport\Console\Command\ExportCommand\Interceptor->Magento\Framework\Interception\{closure}()
#57 ~/projects/acme/generated/code/Tweakwise/Magento2TweakwiseExport/Console/Command/ExportCommand/Interceptor.php(77): Tweakwise\Magento2TweakwiseExport\Console\Command\ExportCommand\Interceptor->___callPlugins()
#58 ~/projects/acme/vendor/symfony/console/Application.php(1021): Tweakwise\Magento2TweakwiseExport\Console\Command\ExportCommand\Interceptor->run()
#59 ~/projects/acme/vendor/symfony/console/Application.php(275): Symfony\Component\Console\Application->doRunCommand()
#60 ~/projects/acme/vendor/magento/framework/Console/Cli.php(115): Symfony\Component\Console\Application->doRun()
#61 ~/projects/acme/vendor/symfony/console/Application.php(149): Magento\Framework\Console\Cli->doRun()
#62 ~/projects/acme/bin/magento(23): Symfony\Component\Console\Application->run()
#63 {main}
```

Expected result
--
List the expected results as a bullet list of expectations
- Compilation successful
- Tweakwise export successful

**Comment by ahuininga-orisha** [comment]
@arnoudhgz This may be an issue with magento 2.4.4. This seems to be the only magento version with this problem.

https://github.com/magento/magento2/issues/35292

Can you try and see if the solution in the link above fixes it for you?

**Comment by onepack** [comment]
This also impacts 2.4.5 versions of Magento.

Upgrading to 2.4.6 fixed this.
